### ISSUE TITLE
Question: how to define "sqlContext"? 

### ISSUE THREAD

**Issue by YiKuanLiu** [deepPhong/icu-readmission#2]
Hi, the result in this paper is great.  I've trying to reproduce your results.
But I encountered this issue.

In your ipython code:

```
loader = DataLoader("mimicomop", tables_dict, measurements_dict)
loader.load(sqlContext)
...
```
But it doesn't seem you've defined the sqlContext.
I've prepared the MIMIC-OMOP database, could you please tell me how to define the **sqlContext**? 
If you can provide an example code for me, that will be very helpful.
I'm a beginner for the SQL, please help me out.

Thank you!

**Comment by xylophong** [comment]
Hi, 

The `sqlContext` is the class created with your Spark session. More info here : https://spark.apache.org/docs/latest/api/python/pyspark.sql.html?highlight=sqlcontext#pyspark.sql.SQLContext
